#!/usr/bin/env bash
set -euo pipefail

SQUID_CONF=${SQUID_CONF:-/etc/squid/squid.conf}
SQUID_CACHE_DIR=${SQUID_CACHE_DIR:-/var/spool/squid}
SQUID_LOG_DIR=${SQUID_LOG_DIR:-/var/log/squid}
ALLOWED_DOMAINS_FILE=/etc/squid/allowed-domains.txt
HELPER_ACLS_FILE=/etc/squid/helper-acls.conf
AGENT_HEADERS_FILE=/etc/squid/agent-headers.conf

# Ensure directories exist with correct ownership
mkdir -p "$SQUID_CACHE_DIR" "$SQUID_LOG_DIR" "$(dirname "$ALLOWED_DOMAINS_FILE")"
chown -R proxy:proxy "$SQUID_CACHE_DIR" "$SQUID_LOG_DIR"

# Generate allowed domains file from environment variable
if [ -n "${SQUID_ALLOWED_DOMAINS:-}" ]; then
    echo "🌐 Configuring allowed domains for Squid proxy..."
    echo "$SQUID_ALLOWED_DOMAINS" | tr ',' '\n' | grep -v '^$' > "$ALLOWED_DOMAINS_FILE"
    echo "✅ Allowed domains configured: $(wc -l < "$ALLOWED_DOMAINS_FILE") domains"
else
    echo "⚠️  No SQUID_ALLOWED_DOMAINS set - defaulting to allow all"
    echo "." > "$ALLOWED_DOMAINS_FILE"
fi

# Ensure helper ACL file exists (may be bind-mounted)
if [ ! -f "$HELPER_ACLS_FILE" ]; then
    cat > "$HELPER_ACLS_FILE" <<'EOF'
# default helper ACLs - allow any helper header using allowed-domains list
acl helper_default req_header X-CA-Helper .
acl helper_default_domains dstdomain "/etc/squid/allowed-domains.txt"
http_access allow helper_default helper_default_domains
EOF
fi

# Generate agent headers to stamp outbound requests (agent/session)
cat > "$AGENT_HEADERS_FILE" <<EOF
# Auto-generated by entrypoint.sh
request_header_add X-CA-Agent ${CA_AGENT_ID:-unknown} all
request_header_add X-CA-Session ${CA_SESSION_ID:-unknown} all
EOF

# Initialize cache if needed
if [ ! -f "$SQUID_CACHE_DIR/00/00000000" ]; then
    echo "🧱 Initializing Squid cache directories..."
    /usr/sbin/squid -z -f "$SQUID_CONF"
fi

# Start Squid in foreground so docker can manage lifecycle
echo "🛡️  Starting Squid proxy (listening on 3128)..."
exec /usr/sbin/squid -N -f "$SQUID_CONF"
