using System.Text;
using System.Text.RegularExpressions;

namespace ContainAI.Cli.Host;

internal interface IDockerProxySshConfigUpdater
{
    Task UpdateAsync(string workspaceName, string sshPort, string remoteUser, TextWriter stderr, CancellationToken cancellationToken);
}

internal sealed class DockerProxySshConfigUpdater : IDockerProxySshConfigUpdater
{
    private readonly IContainAiSystemEnvironment environment;
    private readonly IUtcClock clock;

    public DockerProxySshConfigUpdater(IContainAiSystemEnvironment environment, IUtcClock clock)
    {
        this.environment = environment;
        this.clock = clock;
    }

    public async Task UpdateAsync(string workspaceName, string sshPort, string remoteUser, TextWriter stderr, CancellationToken cancellationToken)
    {
        var sshRoot = Path.Combine(environment.ResolveHomeDirectory(), ".ssh");
        var containAiSshDir = Path.Combine(sshRoot, "containai.d");
        Directory.CreateDirectory(sshRoot);
        Directory.CreateDirectory(containAiSshDir);

        var userConfigPath = Path.Combine(sshRoot, "config");
        const string includeLine = "Include ~/.ssh/containai.d/*.conf";

        if (!File.Exists(userConfigPath))
        {
            await File.WriteAllTextAsync(userConfigPath, includeLine + Environment.NewLine, cancellationToken).ConfigureAwait(false);
        }
        else
        {
            var existing = await File.ReadAllTextAsync(userConfigPath, cancellationToken).ConfigureAwait(false);
            var filtered = existing
                .Split('\n')
                .Where(line => !DockerProxySshConfigRegex.ContainAiIncludeRegex().IsMatch(line))
                .ToArray();

            var merged = includeLine + Environment.NewLine + Environment.NewLine + string.Join(Environment.NewLine, filtered).TrimStart();
            await File.WriteAllTextAsync(userConfigPath, merged.TrimEnd() + Environment.NewLine, cancellationToken).ConfigureAwait(false);
        }

        var hostAlias = $"containai-devcontainer-{workspaceName}";
        var configFile = Path.Combine(containAiSshDir, $"devcontainer-{workspaceName}.conf");
        var builder = new StringBuilder();
        builder.AppendLine($"# ContainAI SSH config for devcontainer: {workspaceName}");
        builder.AppendLine("# Auto-generated by containai-docker mode");
        builder.AppendLine($"# Generated at: {clock.UtcNow:yyyy-MM-ddTHH:mm:ssZ}");
        builder.AppendLine();
        builder.AppendLine($"Host {hostAlias}");
        builder.AppendLine("    HostName localhost");
        builder.AppendLine($"    Port {sshPort}");
        if (!string.IsNullOrWhiteSpace(remoteUser) && !string.Equals(remoteUser, "auto", StringComparison.Ordinal))
        {
            builder.AppendLine($"    User {remoteUser}");
        }

        builder.AppendLine("    StrictHostKeyChecking accept-new");
        builder.AppendLine("    UserKnownHostsFile ~/.ssh/containai.d/known_hosts");
        builder.AppendLine("    PreferredAuthentications publickey,keyboard-interactive");

        await File.WriteAllTextAsync(configFile, builder.ToString(), cancellationToken).ConfigureAwait(false);
        await stderr.WriteLineAsync($"SSH: ssh {hostAlias}").ConfigureAwait(false);
    }
}

internal static partial class DockerProxySshConfigRegex
{
    [GeneratedRegex("^[\\s]*[Ii][Nn][Cc][Ll][Uu][Dd][Ee][\\s]+[^#]*containai\\.d/", RegexOptions.Compiled)]
    public static partial Regex ContainAiIncludeRegex();
}
