namespace ContainAI.Cli.Host;

internal sealed partial class ShellProfileIntegrationService
{
    public bool HasHookBlock(string content)
        => content.Contains(ShellIntegrationStartMarker, StringComparison.Ordinal)
           && content.Contains(ShellIntegrationEndMarker, StringComparison.Ordinal);

    private static string BuildHookBlock()
    {
        var profileDirectory = "$HOME/" + ProfileDirectoryRelativePath;
        return string.Join(
            Environment.NewLine,
            ShellIntegrationStartMarker,
            $"if [ -d \"{profileDirectory}\" ]; then",
            $"  for _cai_profile in \"{profileDirectory}/\"*.sh; do",
            "    [ -r \"$_cai_profile\" ] && . \"$_cai_profile\"",
            "  done",
            "  unset _cai_profile",
            "fi",
            ShellIntegrationEndMarker);
    }

    private static string BuildProfileScript(string homeDirectory, string binDirectory)
    {
        var pathSegment = NormalizePathForShell(homeDirectory, binDirectory);
        return string.Join(
            Environment.NewLine,
            "# Generated by cai install. Manual edits may be overwritten.",
            $"if [ -d \"{pathSegment}\" ]; then",
            $"  case \":$PATH:\" in *\":{pathSegment}:\"*) ;; *) export PATH=\"{pathSegment}:$PATH\" ;; esac",
            "fi",
            "if command -v complete >/dev/null 2>&1; then",
            "  if [ -n \"${ZSH_VERSION-}\" ] && command -v bashcompinit >/dev/null 2>&1; then",
            "    bashcompinit >/dev/null 2>&1 || true",
            "  fi",
            "  _cai_complete()",
            "  {",
            "    local line point",
            "    line=\"${COMP_LINE:-}\"",
            "    point=\"${COMP_POINT:-${#line}}\"",
            "    local IFS=$'\\n'",
            "    COMPREPLY=($(cai completion suggest --line \"$line\" --position \"$point\" 2>/dev/null))",
            "  }",
            "  complete -o default -F _cai_complete cai",
            "  complete -o default -F _cai_complete containai-docker",
            "  complete -o default -F _cai_complete docker-containai",
            "fi",
            string.Empty);
    }
}
