using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ContainAI.EmbeddedAssets.Generator;

[Generator]
public sealed class EmbeddedAssetsSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var parsedResxFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) => ParseResxFile(file, cancellationToken))
            .Where(static parsed => !parsed.Entries.IsDefaultOrEmpty)
            .Collect();

        context.RegisterSourceOutput(parsedResxFiles, static (productionContext, parsedResxFiles) =>
        {
            if (parsedResxFiles.IsDefaultOrEmpty)
            {
                return;
            }

            var allEntries = new SortedDictionary<string, string>(StringComparer.Ordinal);
            foreach (var parsedResxFile in parsedResxFiles.OrderBy(static parsed => parsed.Path, StringComparer.Ordinal))
            {
                foreach (var entry in parsedResxFile.Entries)
                {
                    allEntries[entry.Key] = entry.Value;
                }
            }

            if (allEntries.Count == 0)
            {
                return;
            }

            var source = RenderSource(allEntries);
            productionContext.AddSource("BuiltInAssets.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static ParsedResxFile ParseResxFile(AdditionalText file, CancellationToken cancellationToken)
    {
        var filePath = file.Path ?? string.Empty;
        var content = file.GetText(cancellationToken)?.ToString();
        if (string.IsNullOrWhiteSpace(content))
        {
            return ParsedResxFile.Empty(filePath);
        }

        try
        {
            var document = XDocument.Parse(content);
            var root = document.Root;
            if (root is null)
            {
                return ParsedResxFile.Empty(filePath);
            }

            var entries = ImmutableArray.CreateBuilder<AssetEntry>();
            foreach (var dataElement in root.Elements("data"))
            {
                var keyValue = dataElement.Attribute("name")?.Value;
                if (string.IsNullOrEmpty(keyValue))
                {
                    continue;
                }

                var value = dataElement.Element("value")?.Value;
                entries.Add(new AssetEntry(keyValue!, value ?? string.Empty));
            }

            return new ParsedResxFile(filePath, entries.ToImmutable());
        }
        catch (XmlException)
        {
            return ParsedResxFile.Empty(filePath);
        }
        catch (InvalidOperationException)
        {
            return ParsedResxFile.Empty(filePath);
        }
    }

    private static string RenderSource(SortedDictionary<string, string> allEntries)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Frozen;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.AppendLine("namespace ContainAI.Cli.Host;");
        builder.AppendLine();
        builder.AppendLine("public static class BuiltInAssets");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly FrozenDictionary<string, string> Assets = new Dictionary<string, string>(StringComparer.Ordinal)");
        builder.AppendLine("    {");

        foreach (var entry in allEntries)
        {
            builder
                .Append("        [")
                .Append(ToStringLiteral(entry.Key))
                .Append("] = ")
                .Append(ToStringLiteral(entry.Value))
                .AppendLine(",");
        }

        builder.AppendLine("    }.ToFrozenDictionary(StringComparer.Ordinal);");
        builder.AppendLine();
        builder.AppendLine("    public static IReadOnlyDictionary<string, string> All => Assets;");
        builder.AppendLine();
        builder.AppendLine("    public static bool TryGet(string key, out string value)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (Assets.TryGetValue(key, out var content))");
        builder.AppendLine("        {");
        builder.AppendLine("            value = content;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        value = string.Empty;");
        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static IEnumerable<(string Name, string Content)> EnumerateByPrefix(string prefix)");
        builder.AppendLine("    {");
        builder.AppendLine("        prefix ??= string.Empty;");
        builder.AppendLine();
        builder.AppendLine("        foreach (var asset in Assets)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!asset.Key.StartsWith(prefix, StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                continue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            yield return (asset.Key[prefix.Length..], asset.Value);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ToStringLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 16);
        builder.Append('"');

        foreach (var character in value)
        {
            _ = character switch
            {
                '"' => builder.Append("\\\""),
                '\\' => builder.Append("\\\\"),
                '\0' => builder.Append("\\0"),
                '\a' => builder.Append("\\a"),
                '\b' => builder.Append("\\b"),
                '\f' => builder.Append("\\f"),
                '\n' => builder.Append("\\n"),
                '\r' => builder.Append("\\r"),
                '\t' => builder.Append("\\t"),
                '\v' => builder.Append("\\v"),
                _ => builder.Append(character),
            };
        }

        builder.Append('"');
        return builder.ToString();
    }

    private readonly struct AssetEntry
    {
        public AssetEntry(string key, string value)
        {
            Key = key;
            Value = value;
        }

        public string Key { get; }

        public string Value { get; }
    }

    private readonly struct ParsedResxFile
    {
        public ParsedResxFile(string path, ImmutableArray<AssetEntry> entries)
        {
            Path = path;
            Entries = entries;
        }

        public string Path { get; }

        public ImmutableArray<AssetEntry> Entries { get; }

        public static ParsedResxFile Empty(string path) => new(path, []);
    }
}
