using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ContainAI.EmbeddedAssets.Generator;

public sealed partial class EmbeddedAssetsSourceGenerator
{
    private static void EmitBuiltInAssetsSource(
        SourceProductionContext productionContext,
        ImmutableArray<ParsedResxFile> parsedResxFiles)
    {
        if (parsedResxFiles.IsDefaultOrEmpty)
        {
            return;
        }

        var allEntries = MergeEntries(parsedResxFiles);
        if (allEntries.Count == 0)
        {
            return;
        }

        var source = RenderSource(allEntries);
        productionContext.AddSource("BuiltInAssets.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static SortedDictionary<string, string> MergeEntries(ImmutableArray<ParsedResxFile> parsedResxFiles)
    {
        var allEntries = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var parsedResxFile in parsedResxFiles.OrderBy(static parsed => parsed.Path, StringComparer.Ordinal))
        {
            foreach (var entry in parsedResxFile.Entries)
            {
                allEntries[entry.Key] = entry.Value;
            }
        }

        return allEntries;
    }

    private static string RenderSource(SortedDictionary<string, string> allEntries)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Frozen;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.AppendLine("namespace ContainAI.Cli.Host;");
        builder.AppendLine();
        builder.AppendLine("public static class BuiltInAssets");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly FrozenDictionary<string, string> Assets = new Dictionary<string, string>(StringComparer.Ordinal)");
        builder.AppendLine("    {");

        foreach (var entry in allEntries)
        {
            builder
                .Append("        [")
                .Append(ToStringLiteral(entry.Key))
                .Append("] = ")
                .Append(ToStringLiteral(entry.Value))
                .AppendLine(",");
        }

        builder.AppendLine("    }.ToFrozenDictionary(StringComparer.Ordinal);");
        builder.AppendLine();
        builder.AppendLine("    public static IReadOnlyDictionary<string, string> All => Assets;");
        builder.AppendLine();
        builder.AppendLine("    public static bool TryGet(string key, out string value)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (Assets.TryGetValue(key, out var content))");
        builder.AppendLine("        {");
        builder.AppendLine("            value = content;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        value = string.Empty;");
        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static IEnumerable<(string Name, string Content)> EnumerateByPrefix(string prefix)");
        builder.AppendLine("    {");
        builder.AppendLine("        prefix ??= string.Empty;");
        builder.AppendLine();
        builder.AppendLine("        foreach (var asset in Assets)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!asset.Key.StartsWith(prefix, StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                continue;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            yield return (asset.Key[prefix.Length..], asset.Value);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
